<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <PackageProjectUrl>https://github.com/dotnet/aspire</PackageProjectUrl>
        <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <StrongNameKeyId>Open</StrongNameKeyId>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UsePublicApiAnalyzers>true</UsePublicApiAnalyzers>
    </PropertyGroup>

</Project>