<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <PackageIcon>favicon.PNG</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FlowForge.Net\FlowForge.Net.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Include="..\..\favicon.PNG" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
